package com.ifinance.model;

import com.ifinance.model.base.BaseCustomer;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Customer extends BaseCustomer<Customer> {
	public static final Customer dao = new Customer().dao();
	
	public Follow getFollow(int customerId) {
	       return Follow.dao.findFirst("select * from follow where customer_id = " + customerId + " order by follow_time desc limit 0, 1");
	}
	
	
	public Page<Customer> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from customer order by update_time");
	}
}
