package com.ifinance.model;

import com.ifinance.model.base.BaseFollow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Follow extends BaseFollow<Follow> {
	public static final Follow dao = new Follow().dao();
	
	public int getFollowCount(int customerId)
	{
		Follow follow = dao.findFirst("select count(*) count from follow where customer_id = " + customerId);
		
		return follow.getInt("count");
	}
}
