package com.ifinance.model;

import com.ifinance.model.base.BaseSaleorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Saleorder extends BaseSaleorder<Saleorder> {
	public static final Saleorder dao = new Saleorder().dao();
}
