package com.ifinance.model;

import java.util.List;

import com.ifinance.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
	
	public User getUserByMobile(String mobile)
	{
		return dao.findFirst("select * from user where mobile = '"+mobile+"'");
	}
	
	public List<User> getUsersByPid(int pid)
	{
		return dao.find("select * from user where p_id=" + pid);
	}
	
	
}
