package com.ifinance.model;

import java.util.List;

import com.ifinance.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
	
	public User getUserByMobile(String mobile)
	{
		return dao.findFirst("select * from user where mobile = '"+mobile+"'");
	}
	
	public List<User> getUsersByPid(int pid)
	{
		return dao.find("select * from user where p_id=" + pid);
	}
	
	/**
	 * 今日意向客户
	 * @param childId
	 * @return
	 */
	public int getTodayIntentCount(List<User> allSubUsers)
	{
		User user = dao.findFirst(commonIntentSql(allSubUsers) + " and  to_days(create_time) = to_days(now())");
		
		return user.getInt("count");
	}
	
	/**
	 * 本周意向客户
	 * @param childId
	 * @return
	 */
	public int getWeekIntentCount(List<User> allSubUsers)
	{
		User user = dao.findFirst(commonIntentSql(allSubUsers) + " and  DATE_SUB(CURDATE(), INTERVAL 7 DAY) <= date(create_time)");
		
		return user.getInt("count");
	}
	
	/**
	 * 本月意向客户
	 * @param childId
	 * @return
	 */
	public int getMonthIntentCount(List<User> allSubUsers)
	{
		User user = dao.findFirst(commonIntentSql(allSubUsers) + " and  DATE_FORMAT(create_time,'%Y%m' ) = DATE_FORMAT(CURDATE() , '%Y%m' )");
		
		return user.getInt("count");
	}

	/**
	 * 总意向客户
	 * @param childId
	 * @return
	 */
	public int getTotalIntentCount(List<User> allUsers)
	{
		User user = dao.findFirst(commonIntentSql(allUsers));
		
		return user.getInt("count");
	}
	
	/**
	 * 意向客户统计 common
	 * @param allUsers
	 * @return
	 */
	public String commonIntentSql(List<User> allUsers) {
		StringBuffer sqlInCondition = new StringBuffer();
		for(int i=0; i<allUsers.size(); i++) {
			sqlInCondition.append(allUsers.get(i).getId());
			// 最后一条数据不需要加","
			if (i < (allUsers.size() - 1)) {
				sqlInCondition.append(",");
			}
		}
		
		return "select count(*) count from customer where customer_type not in (0, 100) and user_id in ("+sqlInCondition.toString()+")";
	}
	
	/**
	 * 业绩统计 common
	 * @param allUsers
	 * @return
	 */
	public String commonSaleSql(List<User> allUsers) {
		StringBuffer sqlInCondition = new StringBuffer();
		for(int i=0; i<allUsers.size(); i++) {
			sqlInCondition.append(allUsers.get(i).getId());
			// 最后一条数据不需要加","
			if (i < (allUsers.size() - 1)) {
				sqlInCondition.append(",");
			}
		}
		
		return "select sum(sign_price) summary from Saleorder where user_id in ("+sqlInCondition.toString()+")";
	}
	
	/**
	 * 本周业绩
	 * @param childId
	 * @return
	 */
	public int getWeekSaleCount(List<User> allSubUsers)
	{
		User user = dao.findFirst(commonSaleSql(allSubUsers) + " and  DATE_SUB(CURDATE(), INTERVAL 7 DAY) <= date(create_time)");
		
		return user.getInt("summary");
	}
	
	/**
	 * 本月业绩
	 * @param childId
	 * @return
	 */
	public int getMonthSaleCount(List<User> allSubUsers)
	{
		User user = dao.findFirst(commonSaleSql(allSubUsers) + " and  DATE_FORMAT(create_time,'%Y%m' ) = DATE_FORMAT(CURDATE() , '%Y%m' )");
		
		return user.getInt("summary");
	}
	
}
