package com.ifinance.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFollow<M extends BaseFollow<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
	}

	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

	public void setFollowDesc(java.lang.String followDesc) {
		set("follow_desc", followDesc);
	}

	public java.lang.String getFollowDesc() {
		return getStr("follow_desc");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setVoiceLength(java.lang.Integer voiceLength) {
		set("voice_length", voiceLength);
	}

	public java.lang.Integer getVoiceLength() {
		return getInt("voice_length");
	}

	public void setVoiceUrl(java.lang.String voiceUrl) {
		set("voice_url", voiceUrl);
	}

	public java.lang.String getVoiceUrl() {
		return getStr("voice_url");
	}

	public void setFollowTime(java.util.Date followTime) {
		set("follow_time", followTime);
	}

	public java.util.Date getFollowTime() {
		return get("follow_time");
	}

}
