package com.ifinance.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomer<M extends BaseCustomer<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setSource(java.lang.Integer source) {
		set("source", source);
	}

	public java.lang.Integer getSource() {
		return getInt("source");
	}

	public void setPhoneState(java.lang.Integer phoneState) {
		set("phone_state", phoneState);
	}

	public java.lang.Integer getPhoneState() {
		return getInt("phone_state");
	}

	public void setWechatState(java.lang.Integer wechatState) {
		set("wechat_state", wechatState);
	}

	public java.lang.Integer getWechatState() {
		return getInt("wechat_state");
	}

	public void setSmsState(java.lang.Integer smsState) {
		set("sms_state", smsState);
	}

	public java.lang.Integer getSmsState() {
		return getInt("sms_state");
	}

	public void setCustomerType(java.lang.Integer customerType) {
		set("customer_type", customerType);
	}

	public java.lang.Integer getCustomerType() {
		return getInt("customer_type");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
